### ISSUE TITLE
write automated tests for all components except UI

### ISSUE THREAD

**Issue by kangsoon-dev** [cs2103jan2016-t16-3j/main#114]

**Comment by joanne-huikee** [comment]
Junit test progress for command
- [ ] AddTask
- [ ] BlockSlots
- [ ] Command
- [x] Complete
- [ ] Confirm
- [ ] DeleteTask
- [ ] Edit
- [x] Exit
- [x] Findfree
- [x] Help
- [x] Home
- [ ] Invalid
- [ ] Postponed
- [x] Prioritise
- [ ] Redo
- [ ] Search
- [ ] Setdirectory
- [x] Showarchive
- [x] ShowDetails
- [ ] TaskCommand
- [ ] Undo
