### ISSUE TITLE
(User Story) Dual/Multi Computer Accessibility

### ISSUE THREAD

**Issue by elbatius** [cs2103jan2016-t16-3j/main#13]
As a user, I can access my todo list from either my office or home computer so that I can check my todo list anywhere.

**Comment by joanne-huikee** [comment]
from handbook must-have features:

The ability to specify a specific folder as the data storage location. With this feature, Jim can choose to store the data file in a local folder controlled by a cloud syncing service (e.g. dropbox), allowing him to access task data from multiple computers.
