### ISSUE TITLE
(User Story) Colour - Priority

### ISSUE THREAD

**Issue by elbatius** [cs2103jan2016-t16-3j/main#16]
As a user, I can colour-prioritize my tasks with differing priority levels for better discrimination, instead of a 2-types system (See (User Story) Priority).

**Comment by joanne-huikee** [comment]
(further enhancement) As a user, i can set the status of my task as tentative so that i can block off a period but free out the slot once schedule has been confirmed.

**Comment by kangsoon-dev** [comment]
removed feature
