### ISSUE TITLE
(User Story) Detection of similar commands

### ISSUE THREAD

**Issue by kohkimwee** [cs2103jan2016-t16-3j/main#39]
As a user, my commands that mean similar meanings can get detected, so that I can use similar words to enter the same function.

NOT EXHAUSTIVE!
Add - create
Delete - del/erase/remove/cancel?
Update - modify/mod/change/edit
Display - show/display/ls/list

And other short forms such as tomorrow = (tmr, tml?)

**Comment by kangsoon-dev** [comment]
short forms as medium priority
