### ISSUE TITLE
(User story) Managing tasks through projects

### ISSUE THREAD

**Issue by KhaiVo** [cs2103jan2016-t16-3j/main#45]
As a user, I can add tasks to specific projects so that I can manage them better and have more functionalities

**Comment by kangsoon-dev** [comment]
As a user, after adding specific tasks to different projects, I can map the requirement for each task (for example, task A and B must be done before task C can be done). I can then visually view the mapping of the project course, and find out relevant information from there, such as critical path of the project, expected completion day of the project, project progress, etc

**Comment by kangsoon-dev** [comment]
removed feature
