### ISSUE TITLE
Update Architect

### ISSUE THREAD

**Issue by joanne-huikee** [cs2103jan2016-t16-3j/main#49]
Change architect from:
![image](https://cloud.githubusercontent.com/assets/17000137/13105347/b1ef6cce-d59d-11e5-9d84-5fa6d53e2afe.png)

B to A.2

**Comment by kangsoon-dev** [comment]
GUI - Kang Soon
Parser - Khai
Logic - Kim Wee, Joanne
Storage - Tze Jin
